/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

#include <iostream>
#include <unordered_map>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> m;
        for(char ch : t){
            m[ch]++;
        }
        for(char ch : s){
            m[ch]--;
        }
        for(auto pair : m){
            if(pair.second == 1){
                return pair.first;
            }
        }
        return '\0';
    }
};

int main(){
    Solution sln;
    string s = "mflcd";
    string t = "dlkfcm";
    char ch = sln.findTheDifference(s, t);
    cout << ch << endl;
    return 0;
}